[19기 안정현]Mission.1 django 초기셋팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #10
Opened 2021-04-02 11:06 UTC by ahnjeonghyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:31 UTC, Kang-kyunghun commented
settings.py에서 불필요한 기능 제거와, 추가해야 할 기능이 빠져 있습니다. 
초기셋팅 과정을 한 번 다시 살펴 보세요.

2021-04-05 05:59 UTC, Kang-kyunghun commented
다음 미션 진행해주세요.

2021-04-05 07:53 UTC, Kang-kyunghun requested changes

2021-04-05 07:53 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        input2      = data['password']
id_1, input2는 어떤 변수를 나타내는지 불명확합니다.
```suggestion
        email        = data['email']
        password     = data['password']
```

2021-04-05 07:53 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        elif not email_check.match(id_1) and not phone_check.match(id_1):
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요.
```suggestion
        if not email_check.match(id_1) and not phone_check.match(id_1):
```

2021-04-05 07:53 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        elif len(input2) < 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-05 07:53 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +                    name    = data['name'])
```suggestion
                    email    = data['email'],
                    password = data['password'],
                    nickname = data['nickname'],
                    name     = data['name'])
```

2021-04-05 10:48 UTC, ahnjeonghyun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        elif len(input2) < 8:
넵! 감사합니다

2021-04-05 14:58 UTC, Kang-kyunghun commented
PR template 남겨주세요. PR template 있어야 리뷰 진행 합니다.

2021-04-06 07:52 UTC, Kang-kyunghun requested changes

2021-04-06 07:52 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        pw_length   = 8
상수는 대문자로만 이루어져 있는 것이 컨벤션입니다.

2021-04-06 07:52 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        if User.objects.filter(nickname = nickname):
if문 안에 filter을 사용해서 존재 여부를 판단 잘 하셨습니다. 
일반적으로 if와 filter 을 이용하여 존재 여부를 판단 할 때 .exists()을 붙여서 사용합니다.  filter만 사용할 때는 데이터를 filter 조건에 맞는 쿼리셋 데이터를 가져오지만,  exists()을 사용하면 존재 여부만 판단해서 True 또는 False을 반환 합니다.

2021-04-06 07:52 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +            return JsonResponse({'message':'KEY_ERROR'}, status=400)
key error가 나는 경우를 설명해 주세요(요청)

2021-04-06 22:53 UTC, Kang-kyunghun requested changes

2021-04-06 22:53 UTC, Kang-kyunghun commented on students/jeonghyun-ahn/westagram/users/views.py
> +        login_pw    = data['password']
pw -> password 

변수명을 약자로 줄이지 말아주세요.
회원가입에도 이런 부분이 있다면 같이 수정해 주세요.

2021-04-11 07:35 UTC, closed without merging