[19기 김현영][Mission 1] Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #11
Opened 2021-04-02 11:07 UTC by hyun0k

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- westagram 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- my_setting.py파일에 setting정보 따로 저장

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:28 UTC, Kang-kyunghun requested changes

2021-04-04 08:28 UTC, Kang-kyunghun commented on students/hyunyoung-kim/westagram/settings.py
> +    'user.apps.UserConfig'
(참고) app을 추가하는 방법으로 그냥 app이름만 추가 할 수 있습니다.

2021-04-04 08:41 UTC, hyun0k commented on students/hyunyoung-kim/westagram/settings.py
> +    'user.apps.UserConfig'
넵 감사합니다~!

2021-04-05 02:38 UTC, Kang-kyunghun requested changes

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/models.py
> +    email    = models.CharField(default='', max_length=300, null=False)
(참고)model field 생성시 null=False가 기본 값으로 설정 됩니다.
email이나 passord같이 필수로 들어가야 되는 값에 default로 값을 넣어 주면 값이 안 들어왔을 때도 데이터가 생성됩니다.
필수로 들어가야 된다고 생각되는 값들은 default를 제거해 주세요.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +
불필요한 공백은 제거해 주세요.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +            return JsonResponse({'MESSAGE':'SUCCESS'}, status=200)
try문 안에 해당 내용이 들어가면 어떻게 될까요? try exept 문의 동작 방식을 한 번 생각해 보세요.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +            print('Error occured', e)
에러가 발생 했을 때의 로그를 보기 위해 사용하신 것 같은데, 소스 코드에는 print 지워서 올려주세요.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +            return JsonResponse({'MESSAGE':'SERVER_ERROR'}, status=500)
500 에러는 벡앤드에서 절대 나면 안 되는 에러 입니다. 
500 에러가 났다는 것은 에러가 나는 상황을 컨트롤 하지 못 했다는 이야기가 됩니다. 
따라서 어떤 에러 상황인지 모르고 잡는 exeptions는 의미가 없다고 생각할 수 있습니다.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +                raise InvalidEmail('INVALID_EMAIL_ADDRESS')
raise를 사용하지 않고 바로 return을 하면 가독성이 더 좋지 않을까요?
따로 raise를 사용하신 이유가 exception 파일을 따로 만드셔서 인가요?
장고는 exception을 잘 지원해 줍니다. 특별하게 커스터마이징이 필요하지 않다면 장고에서 지원해주는 exception을 사용하는 것이 좋을 것 같습니다.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/utils.py
> +    return User.objects.filter(nickname=nickname).exists()
위의 validator와 관련된 내용들과 성격이 조금은 다른 것 같습니다. view에 바로 있는 것이 더 적절할 것 같습니다.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/utils.py
> +    return User.objects.filter(email=email).exists()
validator 부분을 따로 빼신 것은 잘 하셨습니다. 따로 빼셨다면, return 값으로 True , False만 반환 하는 것은 어떨까요?
지금은 반환 값으로 로직으로 반환하고 있습니다. 그렇게 반환 한다면, 함수를 따로 분리한 의미가 떨어져 보입니다.

2021-04-05 02:38 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/my_exceptions.py
> +        super().__init__(msg)
따로 exception을 커스터마이징 하신 이유가 있을까요?

2021-04-05 05:41 UTC, hyun0k commented on students/hyunyoung-kim/user/views.py
> +            return JsonResponse({'MESSAGE':'SUCCESS'}, status=200)
try 문 안에 넣어도 동작하긴 하지만 에러가 안났을때 동작할 내용을 분리해서 쓰면 이 코드의 목적이 뭔지 의도가 더 잘드러난다고 생각해서 else문을 사용했습니다. try문 안에 넣는 것이 일반적인 방법인가요?

2021-04-05 07:35 UTC, hyun0k commented on students/hyunyoung-kim/user/utils.py
> +    return User.objects.filter(email=email).exists()
반환되는 값이 그 자체로 Truthy, Falsy 한 값이면  그대로 쓰는 것이 Pythonic한 방법이라고 md파일에 나와있어서 위 방식으로 리턴했는데 따로 분리하면 의미가 없어지는 것인가요?

2021-04-05 14:57 UTC, Kang-kyunghun requested changes

2021-04-05 14:57 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +from .utils                     import validate_email, validate_password
가장 긴 부분에서 한 칸 정도만 띄어 주시면 됩니다.

2021-04-06 01:42 UTC, hyun0k commented on students/hyunyoung-kim/user/views.py
> +from .utils                     import validate_email, validate_password
저거만 수정하고 다음 미션 진행해도 될까요?

2021-04-06 07:39 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-06 12:39 UTC, Kang-kyunghun requested changes

2021-04-06 12:39 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
입력한 아이디가 없다는 것은 데이터베이스에 원하는 정보가 없다는 것이므로 404가 더 적절한 에러 같습니다. 해당 에러에 맞게 메시지도 수정해 주세요.

2021-04-06 12:39 UTC, Kang-kyunghun commented on students/hyunyoung-kim/user/views.py
> +            SECRET_KEY   = SECRET['secret']
코드에서 많이 쓰이지 않고, 가독성을 해치지 않기 때문에 변수에 안 넣고 바로 사용해도 좋을 것 같습니다.

2021-04-07 09:17 UTC, redsaumon commented
수고하셨습니다~~

2021-04-11 07:35 UTC, closed without merging