[19기 이병재] Mission1 Django 초기세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #12
Opened 2021-04-03 02:52 UTC by redgpcmffld

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장고 초기세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 위스타그램 프로젝트 장고 초기세팅 완료

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:22 UTC, Kang-kyunghun requested changes

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/.gitignore
> +/workspace.xml
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/inspectionProfiles/profiles_settings.xml
> +</component>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/misc.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/modules.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/project_westagram.iml
> +</module>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented on students/byeongjae-lee/project_westagram/.idea/vcs.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:22 UTC, Kang-kyunghun commented
미션1에 대한 내용 통과 후 다음 미션 리뷰 진행 하겠습니다.

2021-04-05 01:27 UTC, Kang-kyunghun commented
force push를 하셨네요. 하신 이유가 있을까요?
force push는 rebase 상황 등 특별한 경우를 제외 하고는 사용하면 문제가 될 수 있는 기능입니다.
force push를 사용하신 상황을 코멘트로 남겨 주세요.

2021-04-05 04:39 UTC, redgpcmffld commented
> git push origin feature/byeongjae-lee
To https://github.com/wecode-bootcamp-korea/19-westagram-backend.git
 ! [rejected]        feature/byeongjae-lee -> feature/byeongjae-lee (non-fast-forward)
error: failed to push some refs to 'https://github.com/wecode-bootcamp-korea/19-westagram-backend.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
이런 메세지가 떠서 구글에 검색해보니 +를 붙이면 push가 된다고 해서 했습니다. force push가 뭔지 모르고 그랬습니다. 죄송합니다.

2021-04-05 05:56 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-05 14:59 UTC, Kang-kyunghun commented
아직 미션2 통과하지 않았습니다. 제목 바꿔주세요.

2021-04-06 12:20 UTC, Kang-kyunghun requested changes

2021-04-06 12:20 UTC, Kang-kyunghun commented on students/byeongjae-lee/westagram/users/views.py
> +                    phone_number = data.get('phone_number')
get을 사용한 이유를 적어주세요.(요청)

2021-04-06 12:20 UTC, Kang-kyunghun commented on students/byeongjae-lee/westagram/users/views.py
> +                Q(phone_number=data.get('phone_number'))).exists():
Q을 사용한 이유를 적어주세요.

2021-04-06 12:22 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +                    phone_number = data.get('phone_number')
회원가입 시 이름하고 폰 번호는 입력 안 할때를 대비해서 get으로 바꿨습니다.

2021-04-06 12:23 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +                Q(phone_number=data.get('phone_number'))).exists():
원래 Q를 사용 안 하고 하나하나 구별해서 if문을 쓰니까 코드가 길어져서 바꿨습니다.

2021-04-06 12:36 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +                    phone_number = data.get('phone_number')
해보니까 어차피 키에러 뜨네요 다시 바꾸겠습니다.

2021-04-06 13:56 UTC, Kang-kyunghun requested changes

2021-04-06 13:56 UTC, Kang-kyunghun commented on students/byeongjae-lee/westagram/users/views.py
> +            if not data['phone_number'].isdigit():
.isdigit() 사용한 이유가 무엇인가요?

2021-04-06 14:12 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +            if not data['phone_number'].isdigit():
isdigit()이 문자열 안에 숫자가 있는지 없는지 불리언 값으로 리턴해주기 때문에 전화번호에 숫자가 아닌 값이 들어오면 전화번호가 아니라고 다시 입력해달라고 하려고 썼습니다

2021-04-06 22:42 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +            if not data['phone_number'].isdigit():
전화번호도 정규식으로 거르는게 나을까요?

2021-04-06 22:58 UTC, Kang-kyunghun requested changes

2021-04-06 22:58 UTC, Kang-kyunghun commented on students/byeongjae-lee/westagram/users/views.py
> +            if user := User.objects.filter(
:=의 사용법을 아시나요?

2021-04-06 23:18 UTC, redgpcmffld commented on students/byeongjae-lee/westagram/users/views.py
> +            if user := User.objects.filter(
변수 := 값 조건
해서 조건이 True면 변수에 값이 들어가며 생성이 되는 문법으로 알고 있습니다.
두 줄로 쓸거를 한줄로 줄이기 위해 사용해봤습니다.

2021-04-07 01:32 UTC, Kang-kyunghun commented
미션3 진행하세요~

2021-04-07 09:18 UTC, redsaumon commented
수고하셨습니다!!

2021-04-11 07:35 UTC, closed without merging