[19기 신지원] Mission 1 Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #13
Opened 2021-04-03 08:55 UTC by jeewonn

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission1 초기 세팅을 완료 하였습니다.		 

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- my_settings.py를 추가
- settings.py 수정
- 앱 생성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:17 UTC, Kang-kyunghun requested changes

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/.gitignore
> +/httpRequests/
왜 .gitignore 파일을 2개 만드셨나요?

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.gitignore
> +*.csv
*.csv 파일을 추가하신 이유가 있을까요?

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/inspectionProfiles/profiles_settings.xml
> +</component>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/misc.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/modules.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/vcs.xml
> +</project>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 08:17 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/.idea/westagram.iml
> +  </component>
해당 파일은 github에 올라오면 안 되는 파일입니다.
gitignore에 추가해 주세요.

2021-04-04 09:32 UTC, jeewonn commented
경훈님.... 프로젝트 파일에 있던 .gitignore을 삭제 하고 .idea 폴더에 있던 .gitignore에 올라가면 안된다는 것들 추가했는데...
다른 분들이랑 비교해봤는데.. 저는 애초에 왜 .idea 파일이 올라갔을까요...?
commit도 다 꼬여버린것같아요..ㅠ

2021-04-05 01:18 UTC, jeewonn commented
파이참 사용중이라 gitignore 홈페이지에 들어가서 확인후 추가하였습니다.

2021-04-05 01:36 UTC, Kang-kyunghun commented
gitignore에 추가 잘 하셨습니다.
다음 미션 진행해주세요.

2021-04-05 06:06 UTC, Kang-kyunghun requested changes

2021-04-05 06:06 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/models.py
> +
email이랑 password가 필수 사항이지만, 전화번호 등 회원 가입 때 필요한 정보들도 추가해주세요.

2021-04-05 06:06 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/urls.py
> +    path('/users', UserView.as_view()),
UserView 하나에 회원가입과 로그인을 모두 구현할 예정이신가요?

2021-04-05 06:06 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +        users = User.objects.all()
Users에 모든 회원 정보를 다 가져온 이유가 있을까요?(질문)

2021-04-05 06:06 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +
KeyError와 관련된 부분 추가해 주세요.

2021-04-05 06:06 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/westagram/urls.py
> +
불필요한 공간은 제거해 주세요.

2021-04-05 08:44 UTC, jeewonn commented
1. 모델에 이름과 전화번호를 추가하였습니다.
2. class에서 로그인과 회원가입을 분리하기 위해 이름을 변경을 하였습니다.
3. user회원 정보를 all로 가져오지 않고 filter를 걸었습니다. 
4. KEY ERROR부분은 원래 있었는데.. 혹시 그게 잘 못 되었을까요..? 확인 부탁드립니다.

2021-04-05 09:34 UTC, Kang-kyunghun requested changes

2021-04-05 09:34 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            elif User.objects.filter(email= data['email']).exists():
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-05 09:34 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            elif len(data['password']) <= 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-05 09:34 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +                return JsonResponse({'MESSGAGE': 'This is not valid email.'}, status=400)
- 리턴 메시지는 클라이언트가 보는 것이 아닌고 프론트엔드가 보는 메시지 입니다. 굳이 문장으로 안 하시고, 간단하게 표현해도 좋을 것 같습니다.
- 메시지 형식은 통일하는 것이 좋습니다. 다 대문자로 썼으면 대문자로만, _을 사용해서 단어을 이였다면 계속 _을 사용하는 것처럼요
```suggestion
                return JsonResponse({'MESSGAGE': 'Invalid email.'}, status=400)
```

2021-04-05 09:34 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +                phone_number    = data['phone_number']
가장 긴 단어 기준으로 한 칸 정도만 띄어도 충분할 것 같습니다.

2021-04-05 14:54 UTC, Kang-kyunghun requested changes

2021-04-05 14:54 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +        length_password = 8
상수는 보통 대문자로만 이루어져 있습니다.
```suggestion
        length_password = 8
```
```suggestion
        PASSWORD_LENGTH = 8
```

2021-04-05 14:54 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            if '@' and '.' not in data['email']:
해당 validation 잘 되시나요? @이만 없을 때, .만 없을 때, 둘 다 없을 때 모두 잘 되나요? 확인해 주세요.

2021-04-05 14:54 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            user = User.objects.create(
```suggestion
            if User.objects.filter(email= data['email']).exists():
                return JsonResponse({'MESSGAGE': 'ALREADY USED'}, status=400)
                
            if len(data['password']) <= length_password:
                return JsonResponse({'MESSGAGE': 'INVALID PASSWORD'}, status=400)
                
            user = User.objects.create(
```
공백 추가해서 가독성 높여주세요.

2021-04-06 05:31 UTC, Kang-kyunghun requested changes

2021-04-06 05:31 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +                return JsonResponse({'MESSGAGE': 'INVALID EMAIL'}, status=400)
```suggestion
            if '@' not in data['email'] or '.' not in data['email']::
                return JsonResponse({'MESSGAGE': 'INVALID EMAIL'}, status=400)
```
or 로 조건을 묶을 수 있지 않을까요?

2021-04-06 05:31 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'), bcrypt.gensalt())
비밀번화 암호화 추가 잘 하셨습니다.!!!

- 비밀번화 암호화를 유효성 확인 전에 하는 것도 좋지만, 유효성 확인이 다 끝난 뒤에 하게 되면, 회원가입이 실패 했을 때는 비밀번호를 암호화 하는 과정을 굳이 하지 않아도 됩니다.
- 암호화된 비밀번호를 데이터 베이스에서 확인해 보셨나요? 혹시 b'가 붙어 있지는 않으신가요? 이렇게 데이터가 들어가면 어떠한 문제가 생길까요?

2021-04-06 05:31 UTC, Kang-kyunghun commented
지원님 위에 남긴 코멘트 해결하시면 바로 전한테 와주세요.

2021-04-06 07:34 UTC, Kang-kyunghun reviewed
다음 미션 진행해 주세요.

2021-04-06 13:23 UTC, Kang-kyunghun requested changes

2021-04-06 13:23 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +                    return JsonResponse({'MESSAGE': 'NO VALIED'}, status=401)
if를 많이 줄이셨군요!!! 잘 하셨습니다~
존재하지 않는 조건을 먼저 하게 되면 else가 없어도 되지 않을까요?

2021-04-06 13:23 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            return JsonResponse({'MESSGAGE': 'SUCCESS'}, status=200)
비밀번호가 틀렸을 경우는 어떻게 하면 좋을까요?

2021-04-06 13:23 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +                    return JsonResponse({'MESSAGE': 'NO VALIED'}, status=401)
입력한 아이디와 일치하는 정보가 없다는 것은 데이터베이스에 원하는 정보가 없다는 뜻이므로 에러 코드는 404가 더 적절할 것 같습니다. 이에 맞게 에러 메시지도 수정해 주세요.

2021-04-07 07:44 UTC, Kang-kyunghun requested changes

2021-04-07 07:44 UTC, Kang-kyunghun commented on students/jeewon-shin/westagram/user/views.py
> +            x = User.objects.filter(nickname=data['nickname'])
변수이름은 어떤 변수를 나타내는지 명확히 나타내는 것으로 해주세요.
아래 print도 지워주세요.

2021-04-08 00:47 UTC, Kang-kyunghun commented
구두로 같이 수정한 부분 push 하시면 완료입니다~.

2021-04-11 07:35 UTC, closed without merging