[19기 정재유] Mission 1 Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #14
Opened 2021-04-03 09:03 UTC by deonii

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:12 UTC, Kang-kyunghun commented
Mission1 완료!! 다음 mission 진행해주세요.

2021-04-05 06:17 UTC, Kang-kyunghun requested changes

2021-04-05 06:17 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/models.py
> +class Signin(models.Model):
회원가입, 로그인은 모두 유저의 정보를 가지고 작업이 이루어 집니다.
따라서 table이 signin과 관련된 정보가 아닌 유저와 관련된 정보를 명시하게 해주세요.

2021-04-05 06:17 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +            if len(data['password']) < 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-05 06:17 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "비밀번호는 8자리 이상으로 만들어 주세요."}, status=400)
리턴 메시지는 클라이언트에게 보내는 것이 아니고 프론트에게 보내는 것입니다. 굳이 한글로 친절하게 알려주시지 않으셔도 됩니다.
```suggestion
                return JsonResponse({"message": "INVALID_PASSWORD"}, status=400)
```

2021-04-05 07:20 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/models.py
> +class Signin(models.Model):
네 수정했습니다.

2021-04-05 07:21 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +            if len(data['password']) < 8:
네 수정했습니다.

2021-04-05 07:22 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "비밀번호는 8자리 이상으로 만들어 주세요."}, status=400)
네 수정했습니다.

2021-04-05 08:07 UTC, Kang-kyunghun requested changes

2021-04-05 08:07 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +        password_length = 8
상수는 보통 대문자로만 이루어져 있습니다.

2021-04-05 08:07 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/models.py
> +class UserInfo(models.Model):
User라는 class 명만으로도 충분히 UserInfor을 내포 합니다.
```suggestion
class User(models.Model):
```

2021-04-05 08:07 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +        return JsonResponse({"message": "Success"}, status=201)
유저 정보가 create 되고 바로 return 되는 것이 더 가독성이 좋고. 논리적으로도 맞는 것 같습니다.

2021-04-05 08:07 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
위의 if가 만족하여 return이 됩니다. 따라서 굳이 elif로 조건을 묶지 않아도 if만으로 해결이 가능합니다.

2021-04-05 14:51 UTC, Kang-kyunghun requested changes

2021-04-05 14:51 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/models.py
> +    user_name    = models.CharField(max_length=100)
이미 user 정보에 대한 테이블이므로 name만으로도 충분히 user의 name을 의미합니다.

2021-04-05 14:51 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/urls.py
> +        path('/signin', Sign.as_view())
signup에 관한 url인가요? signin에 관한 url인가요? 확인해 주세요.

2021-04-05 14:51 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +from django.http import JsonResponse
import 라인 맞춰주세요.

2021-04-05 14:51 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +            return JsonResponse({"message": "Success"}, status=201)
리턴 메시지 형식은 통일 시켜주는 것이 좋습니다. 
대문자로만 갔다면, 계속 대문자로만 보내주세요.

2021-04-05 14:51 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
```suggestion
            if len(data['password']) < PASSWORD_LENGTH:
                return JsonResponse({"message": "INVALID_PASSWORD"}, status=400)
                
            if not  email_validation(data['email']):
                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
```
if 문 사이에 공백 추가하여 가독성 높여주세요.

2021-04-06 01:29 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +        password_length = 8
네 수정했습니다.

2021-04-06 01:29 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/models.py
> +class UserInfo(models.Model):
네 수정했습니다.

2021-04-06 01:29 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +        return JsonResponse({"message": "Success"}, status=201)
네 수정했습니다.

2021-04-06 01:29 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
네 수정했습니다.

2021-04-06 01:40 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/models.py
> +    user_name    = models.CharField(max_length=100)
name으로 수정했습니다.

2021-04-06 01:40 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/urls.py
> +        path('/signin', Sign.as_view())
signup으로 수정했습니다.

2021-04-06 01:42 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +from django.http import JsonResponse
import라인 맞춘다는게 json과 bcrypt의 순서를 바꿔줘서 아래 from django.http import JsonResponse과 가깝게 하는것 인가요?

2021-04-06 01:42 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +            return JsonResponse({"message": "Success"}, status=201)
수정했습니다.

2021-04-06 01:45 UTC, deonii commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "INVALID_EMAIL"}, status=400)
네 수정했습니다.

2021-04-06 07:33 UTC, Kang-kyunghun requested changes
라인만 맞춰주시고, 다음 미션 진행해 주세요.

2021-04-06 07:33 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/models.py
> +    name    = models.CharField(max_length=100)
라인 맞춰주세요.

2021-04-06 07:33 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +from django.http import JsonResponse
from xxx import xxx 여기에서 import들을 맞추라는 이야기 입니다.

2021-04-06 14:00 UTC, Kang-kyunghun requested changes

2021-04-06 14:00 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status=401)
- 비밀번호가 일치하지 않는 경우를 먼저 생각한다면 else가 필요없지 않을까요?

2021-04-06 14:00 UTC, Kang-kyunghun commented on students/Jaeyou-Jeong/westagram/users/views.py
> +                    Signin_User = User.objects.get(phone_number=data['account'])
일반적인 변수명은 소문자로 사용합니다.

2021-04-08 00:47 UTC, Kang-kyunghun commented
구두로 같이 수정한 것까지 push 하시면 완료입니다.

2021-04-11 07:35 UTC, closed without merging