[19기 서득영]Mission 1 Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #15
Opened 2021-04-03 17:08 UTC by ulr0

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:09 UTC, Kang-kyunghun requested changes
PR 남기 때 taplate에 작업한 내용 적어 주세요.

2021-04-04 08:09 UTC, Kang-kyunghun commented on students/deukyeong-seo/westagram/westagram/settings.py
> +]
user app을 생성 하셨습니다. app을 생성한 뒤에 어떤 작업을 해야 django가 app이 생성되었는지 알 수 있을까요?

2021-04-04 12:57 UTC, Kang-kyunghun commented
미션1 완료!! 
다음 미션 진행해주세요.

2021-04-06 06:45 UTC, redsaumon commented on students/deukyeong-seo/westagram/user/models.py
> +        db_table = 'users'
컨벤션 완벽하네요~

2021-04-06 06:45 UTC, redsaumon commented on students/deukyeong-seo/westagram/user/views.py
> +            return JsonResponse({'message':'SUCCESS'}, status=201)
status=201 굿입니다~ 공백만 줄여주시면 완벽!

2021-04-06 06:45 UTC, redsaumon commented on students/deukyeong-seo/westagram/user/views.py
> +                return JsonResponse({'message':'INVALID_EMAIL'}, status=400)
이렇게 해도 되겠지만 @과 .으로만 이메일 형식을 잡아주면 조금 허술하지 않을까요?

2021-04-06 12:18 UTC, Kang-kyunghun requested changes

2021-04-06 12:18 UTC, Kang-kyunghun commented on students/deukyeong-seo/westagram/user/views.py
> +                return JsonResponse({'message':'DUPLICATE_EMAIL'}, status=400)
데이터베이스에 접근하여 이메일 중복 여부를 판단하는 것이 유효성 검사가 모두 완료된 뒤에 하는 것이 더 효율적입니다.
해당 코드는 유효성 검사가 끝난 뒤로 옮겨주세요.

2021-04-06 12:18 UTC, Kang-kyunghun commented
위의 코멘트만 수정하시고, 다음 미션 진행해 주세요.

2021-04-07 07:41 UTC, Kang-kyunghun requested changes

2021-04-07 07:41 UTC, Kang-kyunghun commented on students/deukyeong-seo/westagram/user/views.py
> +            if email_check == None:
None을 비교할 때는 == 보다는 is를 사용합니다.

2021-04-07 07:41 UTC, Kang-kyunghun commented on students/deukyeong-seo/westagram/user/views.py
> +                return JsonResponse({'message':'NOT_FOUND'}, status=404)
if와 else을 사용해서 구성 잘 하셨습니다.
그런데 만약에 로직에서 로그인이 실패하는 경우를 먼저 나오게하면 else들을 없애고 가독성도 높일 수 있을 것 같습니다.
한 번 생각해 보시고 수정해 보세요.

2021-04-11 07:35 UTC, closed without merging