[19기 함경재] Mission1 Django 초기 셋팅
wecode-bootcamp-korea/19-westagram-backend pull request #16
Opened 2021-04-04 01:41 UTC by hiyee-gj

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 장고 프로젝트 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 초기 세팅 완료(installed app에 app 추가하는 것 제외)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:06 UTC, Kang-kyunghun requested changes

2021-04-04 08:06 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/westagram/settings.py
> +]
users app을 생성 하셨군요~! app을 생성한 뒤에 어떤 작업을 해야 django에서 해당 app이 생성 되었는지 알 수 있을까요?

2021-04-04 08:17 UTC, hiyee-gj commented on students/gyeongjae-ham/westagram/westagram/settings.py
> +]
installed app에 추가한것만 올리고 싶었는데 mission 2까지 진행한 내용을 올려버렸네요

2021-04-04 08:19 UTC, Kang-kyunghun commented
Mission1 완료 다음 미션 진행해 주세요

2021-04-05 06:55 UTC, Kang-kyunghun requested changes

2021-04-05 06:55 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/urls.py
> +    path('/createuser', CreateUserView.as_view())
(참고)회원가입일 경우 일반적으로 signup을 많이 사용합니다.

2021-04-05 06:55 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/urls.py
> +    path('/createuser', CreateUserView.as_view()),
(참고) 일반적으로 회원가입은 signup이라는 표현을 많이 사용합니다.

2021-04-05 06:55 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'이미 등록된 이메일입니다.'}, status=400)
리턴 메시지는 클라인언트가 보는 것이 아니고 프론트가 보는 메시지 입니다. 그래서 굳이 한글로 친절하게 안 보내셔도 됩니다.
다음 메시지가 일반적입니다.
```suggestion
                return JsonResponse({'MESSAGE':'DUPLICATED_EMAIL'}, status=400)
```

2021-04-05 06:55 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +
공백 제거해주세요.

2021-04-05 06:55 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +        return JsonResponse({'MESSAGE': 'SUCCESS'}, status=200)
성공 리턴은 유저가 성공적으로 만들어지는 코드 다음에 오는 것이 가독성이 좋습니다.
수정해 주세요.

2021-04-05 08:28 UTC, Kang-kyunghun requested changes

2021-04-05 08:28 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +            elif User.objects.filter(name=data['name']).exists():
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-05 08:28 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/models.py
> +    number   = models.CharField(max_length=45)
number가 핸드폰 번호를 의미 하시나요?
어떤 번호인지 명확하게 변수를 정해주세요.

2021-04-05 14:45 UTC, Kang-kyunghun requested changes

2021-04-05 14:45 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'DUPLICATED_NAME'}, status=400)
```suggestion
            if User.objects.filter(email=data['email']).exists():
                return JsonResponse({'MESSAGE':'DUPLICATED_EMAIL'}, status=400)
                
            if User.objects.filter(name=data['name']).exists():
                return JsonResponse({'MESSAGE':'DUPLICATED_NAME'}, status=400)
```
if 문 사이에 공백 축가하여 가독성 높여주세요.

2021-04-06 07:27 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-06 12:16 UTC, Kang-kyunghun requested changes

2021-04-06 12:16 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALIED_NUMBER'}, status=400)
유효성 검사를 모두 완료한 뒤에 데이터베이스에 접근하는 것이 더 효율적이지 않을까요?

2021-04-06 12:24 UTC, hiyee-gj commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALIED_NUMBER'}, status=400)
넵!!!!

2021-04-06 13:46 UTC, Kang-kyunghun requested changes

2021-04-06 13:46 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +            if data['account']:
데이터가 들어오지 않는다면 key error로 넘어가기 때문에 가장 위에 있는 if는 무의미해 보입니다.

2021-04-06 13:46 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALIED_PASSWORD'}, status=400)
비밀번호가 틀렸다는 것은 권한이 없다는 이야기가 됩니다. 해당 상황에서 적절한 에러 코드는 무엇일까요?

2021-04-06 13:46 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'INVALIED_PASSWORD'}, status=400)
비밀번호가 일치하지 않는 상황을 먼저 생각한다면, 뒤에 else가 없어도 되지 않을까요?

2021-04-07 07:38 UTC, Kang-kyunghun commented
위의 오타인지 한 번만 확인해 주세요.
고생하셨습니다.

2021-04-07 07:38 UTC, Kang-kyunghun requested changes

2021-04-07 07:38 UTC, Kang-kyunghun commented on students/gyeongjae-ham/westagram/users/views.py
> +                token = jwt.encode({'user_id':user.id}, SECRET_KEY, algorithm=HS)
알고리즘 오타인가요?

2021-04-07 07:46 UTC, hiyee-gj commented on students/gyeongjae-ham/westagram/users/views.py
> +                token = jwt.encode({'user_id':user.id}, SECRET_KEY, algorithm=HS)
아뇨 알고리즘도 my_settings에 숨겨서 가져온 변수명입니다!!

2021-04-11 07:35 UTC, closed without merging