[19기 윤서준] Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #19
Opened 2021-04-04 09:42 UTC by Johnywhisky

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 초기 세팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 가상환경 설정
- settings.py 수정
- ignore 적용
- urls 및 views 설정

## 기타 질문 및 특이 사항
비밀번호 hash화 같은 간단한 암호화(?)를 위해 따로 파이썬 hashing.py(예를들어) 작성 후 views or models에 import하는 방식으로 해도 괜찮을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

2021-04-04 12:48 UTC, Kang-kyunghun commented
미션1 완료~!! 다음 미션 진행해주세요.

2021-04-05 06:18 UTC, Johnywhisky commented
push했더니 이곳에 덮어쓰기가 됐어요!!!

2021-04-05 08:34 UTC, Kang-kyunghun requested changes

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/models.py
> +    user_phone    = models.CharField(max_length = 11)
- 이미 유저 정보에 대한 테이블이기 때문에 user_ 다 빼주세요.
- id 대신 email을 받는 것이 필수사항입니다.
- 변수명을 줄여 쓰지 말고 끝까지 써주세요. ex) pw -> password

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +        pw_validation    = re.compile('[(<`~!@#$%^&*,./?;:>)]+')
변수명 줄여 사용한 것 고쳐주세요.

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +        # ID Validation check. 1st if > 중복 확인
주석은 전부 제거해 주세요.

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +            return JsonResponse({'message': 'KEY_ERROR ID already exist'}, status = 400)
KeyError가 어떤 상황에 발생하는지 다시 한 번 생각해 보세요.

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +        if len(data['user_pw']) < 8 or len(data['user_pw']) > 30:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-05 08:34 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +                                user_phone    = data['user_phone'],
가장 긴 변수에서 한 칸만 띄어주세요.

2021-04-05 14:41 UTC, Kang-kyunghun requested changes
-  정규표현식에 관한건 만나서 이야기 해봐요
- 왜 모든 error 메시지에 key error라는 말이 붙어 있나요?(질문)

2021-04-05 14:41 UTC, Kang-kyunghun commented on students/project_westagram/accounts/models.py
> +    min_phone    = 10
테이블과 관련되지 않은 내용들 제거해 주세요.

2021-04-05 14:41 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +        min_phone    = Accounts.min_phone
모델에서 가져오지 말고 view에서 상수로 만드세요.

2021-04-06 01:02 UTC, Johnywhisky commented
> * ror
왜 모든 error 메시지에 key error라는 말이 붙어 있나요?(질문)
 a) 처음에 미션을 이해할 때 잘못 이해해서 모든 리턴에 key error를 추가해야한는 줄 알았습니다. 에러값에 맞게 리턴할 수 있게 수정할게요

2021-04-06 08:23 UTC, Kang-kyunghun requested changes

2021-04-06 08:23 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +        min_phone    = 10
상수는 대문자로 만드는 것이 컨벤션 입니다.

2021-04-06 08:23 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +                return JsonResponse({'message': "Invalid email"}, status = 400)
if 문들 사이에 공백을 추가하여 가독성을 높여주세요.

2021-04-06 08:23 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +                return JsonResponse({'message': 'Invalid Password(각 하나 이상의 소문자 또는 대문자 그리고 숫자를 포함하세요)'}, status = 400)
- 리턴 메시지는 클라이언트가 보는 것이 아닌고 프론트엔드가 보는 메시지 입니다. 굳이 문장으로 안 하시고, 간단하게 표현해도 좋을 것 같습니다.

2021-04-06 08:23 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +            return JsonResponse({'message': f"KEY ERROR! '{error_source}' is incorrect"}, status = 400)
```suggestion
            return JsonResponse({'message': "KEY ERROR!"}, status = 400)
```
- 리턴 메시지는 클라이언트가 보는 것이 아닌고 프론트엔드가 보는 메시지 입니다. 굳이 문장으로 안 하시고, 간단하게 표현해도 좋을 것 같습니다.

2021-04-06 12:14 UTC, Kang-kyunghun requested changes

2021-04-06 12:14 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +                return JsonResponse({'message': "Already exist phone"}, status = 400)
유효성 검사를 모두 완료하고 데이터베이스에 접근하는 것이 더 효율적이지 않을까요?

2021-04-06 12:14 UTC, Kang-kyunghun commented on students/project_westagram/accounts/views.py
> +
공백 1칸 제거해 주세요.

2021-04-06 12:16 UTC, Johnywhisky commented on students/project_westagram/accounts/views.py
> +                return JsonResponse({'message': "Already exist phone"}, status = 400)
각 key word 별로 해당하는 검사를 수행했었는데, 수정하겠습니다 :)

2021-04-11 07:35 UTC, closed without merging