first-version of mission 2
wecode-bootcamp-korea/19-westagram-backend pull request #20
Opened 2021-04-04 10:08 UTC by poketsc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

- 초기셋팅 and 회원가입 작성 
		 

## 기타 질문 및 특이 사항

- 이메일, 전화번호를 한 컬럼으로 처리했습니다 (identification)
- 이러한 경우에 예외처리를 전화번호, 이메일을 따로 구현할수 있는 방법이 있을까요?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 14:09 UTC, Kang-kyunghun commented
미션1 완료! 
다음 미션 진행해주세요.

2021-04-05 08:38 UTC, Kang-kyunghun requested changes

2021-04-05 08:38 UTC, Kang-kyunghun commented on students/seungchan-baek/user/models.py
> +    identification = models.CharField(max_length=50)
identification의 역할로 email을 사용하고 있습니다.

2021-04-05 08:38 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +        except KeyError:
Keyerror가 언제 발생하는지 확인하고, 현재 코드에서 keyerror가 발생할 수 있는지, 확인해 보세요.

2021-04-05 08:38 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +            elif User.objects.filter(nickname=nickname):
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-05 08:38 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +                return JsonResponse({'MESSAGE':'NICKNAME_ALREADY_EXIST'}, status=400)
메시지 형식은 통일시켜주는 것이 좋습니다. _을 사용했다면, 계속 사용하고, 아니면 전부 제거해 주세요.

2021-04-05 10:30 UTC, poketsc commented on students/seungchan-baek/user/models.py
> +    identification = models.CharField(max_length=50)
경훈님 저는 identification 에 phone_number, email 타입이 다 들어갈수 있게 처리했습니다~ 그래서 명칭을 identification이라고 두가지 의미를 다 담을수 있게 만들었습니다 이런 경우에도 email로 바꿔야 되나요? 아니면 email로 바꾸고 phone_number 컬럼도 따로 만들라고 말씀하신건가요? 의미가 헷갈려서 코멘트 남깁니다~

2021-04-05 14:37 UTC, Kang-kyunghun commented
model 수정이 아직 안 되어 있네요. 수정해 주세요.

2021-04-06 07:26 UTC, Kang-kyunghun requested changes
마지막 코멘트만 확인해 보시고 다음 미션 진행해 주세요.

2021-04-06 07:26 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +            else:
위의 로직상 else가 없어도 정상적으로 동작하지 않을까요?

2021-04-06 12:10 UTC, Kang-kyunghun requested changes
아래 코멘트 내용만 반영하시고 다음 미션 진행해 주세요.

2021-04-06 12:10 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_PASSWORD'}, status=400)
유효성 검사가 완료 모두 완료 된 뒤에 데이터 베이스에 접근하는 것이 더 효율적이지 않을까요?

2021-04-06 13:41 UTC, Kang-kyunghun requested changes

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +
공백은 1칸으로 충분합니다~!!

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +                raise KeyError
key error을 except로 빼셨다면 이렇게 하기 보다는  password처럼 데이터를 받는 것은 어떨까요? try문 안에 data 받는 부분이 포함 되어 있다면 if 없이도 충분히 key error을 잡을 수 있을 것 같습니다.

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +                    return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
위에서 key error을 잡았다면 첫번째 if는 불필요해 보입니다. 위에 코멘트를 활용한다면, 데이터 받는 것과 key error을 동시에 해결할 수 있다고 생각 됩니다.

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +                    return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
입력한 아이디가 없다는 것은 데이터베이스에 원하는 정보가 없다는 것이므로 404가 더 적절한 에러 같습니다. 해당 에러에 맞게 메시지도 수정해 주세요.

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +
비밀번호가 일치하지 않는 조건을 먼저 생각한다면 뒤에 오는 else가 필요업지 않을까요?
한 번 생각해 보세요.

2021-04-06 13:41 UTC, Kang-kyunghun commented on students/seungchan-baek/user/views.py
> +
불필요한 공백은 제거해 주세요.

2021-04-11 07:35 UTC, closed without merging