[19기 양명진] [Mission 2] 회원가입 엔드포인트
wecode-bootcamp-korea/19-westagram-backend pull request #21
Opened 2021-04-04 12:21 UTC by audwls624

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 12:59 UTC, Kang-kyunghun requested changes
practice.py 이 파일은 불필요해 보입니다. 파일 지워주시고, 다음 미션 진행해 주세요~~!!!

2021-04-05 08:45 UTC, Kang-kyunghun requested changes

2021-04-05 08:45 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/models.py
> +    identity       = models.CharField(max_length=45)
- identity의 역할로 email을 사용하고 있습니다.
- 가장 긴 변수에서 한 칸만 띄어 주세요.

2021-04-05 08:45 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/views.py
> +            elif len(password)<8:
- 위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요

- 비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-05 08:45 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/views.py
> +            return JsonResponse({'message':"SUCCESS"}, status=200)
에러가 없이 정상적으로 코드가 전부 실행 되었을 때 성공 리턴하게 잘 하셨습니다.
그런데, user 정보가 잘 생성 뒤에 성공 리턴을 해주는 것이 가독성 면에서 훨씬 좋습니다.

2021-04-05 10:09 UTC, audwls624 commented on students/myeongjin-yang/westagram/users/models.py
> +    identity       = models.CharField(max_length=45)
```suggestion
    identity       = models.CharField(max_length=45)
```

2021-04-05 10:11 UTC, audwls624 commented on students/myeongjin-yang/westagram/users/models.py
> +    identity       = models.CharField(max_length=45)
- identity 역할로 email, 휴대폰번호를 동시에 사용하여서 CharField 사용하였습니다.

2021-04-05 14:59 UTC, Kang-kyunghun commented
아직 미션2 통과하지 않았습니다. 제목 바꿔주세요.

2021-04-06 07:11 UTC, Kang-kyunghun requested changes

2021-04-06 07:11 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/views.py
> +            else:
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 else로 조건을 묶으시지 않으셔도 됩니다.
아래 elif, else들도 정말 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-06 22:57 UTC, Kang-kyunghun requested changes

2021-04-06 22:57 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/views.py
> +                return JsonResponse({'message':"Invalid PW"}, status=400)
유효성 검사가 데이터베이스에 접근하는 로직보다 위에 있는 것이 더 효율적이지 않을까요?

2021-04-06 22:57 UTC, Kang-kyunghun commented on students/myeongjin-yang/westagram/users/views.py
> +            return JsonResponse({'message':"KEY_ERROR"}, status=400)
except는 가독성을 위해 코드 가장 아래에 위치 하는 것이 좋습니다.

2021-04-11 07:35 UTC, closed without merging