[19기 김영훈] Mission1 Django 초기 세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #22
Opened 2021-04-04 12:38 UTC by fcfargo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- django 초기 세팅 완료했습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 프로젝트 폴더 및 app 생성
- settings.py 수정
- urls.py 수정
- views.py  수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 12:42 UTC, Kang-kyunghun requested changes

2021-04-04 12:42 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/project_westagram/settings.py
> +SECRET_KEY = 'a351wwz0q6tx(gh%(b($dey!w)u^=ol#q-k9w)zi!qhrqk5i@='
SECRET_KEY는 my_settings 파일을 만들어서 따로 빼주세요.

2021-04-04 12:42 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/project_westagram/settings.py
> +DATABASES = {
Database는 my_settings 파일을 만들어서 따로 빼주시고, MySql로 셋팅해 주세요.

2021-04-04 13:40 UTC, fcfargo commented on students/younghun-kim/project_westagram/project_westagram/settings.py
> +DATABASES = {
Database 내용을 my_settings.py로 옮긴 뒤, django와 mysql을 연결했습니다.

2021-04-04 13:42 UTC, fcfargo commented on students/younghun-kim/project_westagram/project_westagram/settings.py
> +SECRET_KEY = 'a351wwz0q6tx(gh%(b($dey!w)u^=ol#q-k9w)zi!qhrqk5i@='
SECRET_KEY의 내용을 생성된 my_sttings.py로 옮겼습니다.

2021-04-04 14:11 UTC, Kang-kyunghun commented
미션1 완료~
다음 미션 진행해주세요.

2021-04-05 08:51 UTC, Kang-kyunghun requested changes

2021-04-05 08:51 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/models.py
> +    password  = models.CharField(max_length=64)
- 이미 user의 정보를 담고 있는 테이블이므로 useremail -> email로 바꿔주세요.
- email, password 이외에 회원가입 할 때 기본적으로 필요할 수 있는 정보들도 추가해 주세요.

2021-04-05 08:51 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/urls.py
> +    path('/register', RegisterView.as_view()),
register라는 것은 유저를 등록할 수도 있고, 상품을 등록할 수도 있습니다. 그래서 일반적으로 회원가입은 signup이라는 표현을 사용합니다.

2021-04-05 08:51 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +        re_password = data['re_password']
(참고)패스워드 재입력 같은 경우 프론트에서 주로 하는 validation 입니다.

2021-04-05 15:38 UTC, fcfargo commented on students/younghun-kim/project_westagram/users/models.py
> +    password  = models.CharField(max_length=64)
수정 사항을 반영했습니다.

2021-04-05 15:38 UTC, fcfargo commented on students/younghun-kim/project_westagram/users/urls.py
> +    path('/register', RegisterView.as_view()),
수정 사항을 반영했습니다.

2021-04-05 15:38 UTC, fcfargo commented on students/younghun-kim/project_westagram/users/views.py
> +        re_password = data['re_password']
수정 사항을 반영했습니다.

2021-04-06 07:21 UTC, Kang-kyunghun requested changes

2021-04-06 07:21 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +        if len(password) < 8:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-06 07:21 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +            return JsonResponse({"message":"Password must be at least 8 characters"}, status = 400)
- 리턴 메시지는 클라이언트가 보는 것이 아닌고 프론트엔드가 보는 메시지 입니다. 굳이 문장으로 안 하시고, 간단하게 표현해도 좋을 것 같습니다.

2021-04-06 07:21 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +        else:
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 else로 조건을 묶으시지 않으셔도 됩니다.
아래 else도 정말 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-06 07:21 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +        if not (email and password):
key error가 언제 발생하는지 설명해주세요. (요청)

2021-04-06 07:37 UTC, fcfargo commented on students/younghun-kim/project_westagram/users/views.py
> +        if not (email and password):
피드백 내용이 잘 이해가 안되서 여쭙습니다.  JsonResponse의 message 부분에  key error 발생 이유에 관한 내용을 추가하라는 말씀이신가요???

2021-04-06 12:08 UTC, Kang-kyunghun requested changes
아래 코맨트에 대해 수정 하시고 바로, 다음 미션 진행해 주세요.

2021-04-06 12:08 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +        PASSWORD_LENGTH = 8
상수는 보통 코드 상단에 위치하게 합니다. 그래야 찾기가 쉬워집니다.

2021-04-06 12:08 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +            return JsonResponse({"message":"KEY_ERROR"}, status = 400)
가독성을 위해서 except 문은 코드 제일 아래 쪽으로 내려 주시는 것이 좋을 것 같습니다.

2021-04-06 22:49 UTC, Kang-kyunghun requested changes
if를 기준으로 코드가 중복되고 있습니다. 중복 없이 어떻게 할 수 있을까요?

2021-04-06 22:49 UTC, Kang-kyunghun commented on students/younghun-kim/project_westagram/users/views.py
> +                user_password = user[0].password
인덱스를 사용하여 데이터를 가져오는 것은 좋지 않습니다.

2021-04-11 07:35 UTC, closed without merging