[19기 유동헌] Mission1 Django 초기셋팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #23
Opened 2021-04-04 13:21 UTC by dhhyy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission1 Django 초기셋팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 14:13 UTC, Kang-kyunghun commented
미션1 완료
다음 미션 진행해 주세요.

2021-04-06 13:26 UTC, Kang-kyunghun requested changes

2021-04-06 13:26 UTC, Kang-kyunghun commented on students/dongheon-yu/westagram/users/views.py
> +        if len(password) < 6:
비밀번호 길이가 8보다 작을 때 조건을 잘 만드셨습니다.
그런데, 나중에 기획이 바뀌어서 길이가 10보다 작을 때로 바뀌면 숫자 부분을 바꿔야 합니다. 지금은 1부분에서만 사용 했기 때문에 쉽게 바꿀 수 있지만, 나중에 프로젝트가 커지고 저러한 부분이 많이 사용 되었다면, 한 번 수정 할 때 어려움이 있습니다. 그래서 이럴 경우에는 상수를 하나 만들어서 거기에 데이터를 저장해서 사용합니다.

2021-04-06 13:26 UTC, Kang-kyunghun commented on students/dongheon-yu/westagram/users/views.py
> +            pass
try except 문의 사용법이 잘 못 되었습니다.

2021-04-06 13:26 UTC, Kang-kyunghun commented on students/dongheon-yu/westagram/users/views.py
> +            return JsonResponse({"message" : "아이디를 제대로 써주세요"}, status = 401)
해당 코드 작성 후 원하는데로 혹시 작동했나요?

2021-04-08 04:59 UTC, dhhyy commented on students/dongheon-yu/westagram/users/views.py
> +            return JsonResponse({"message" : "아이디를 제대로 써주세요"}, status = 401)
잘 작동하지 않았습니다.
괄호 안에 조건을 'and'로 수정하였습니다.

2021-04-11 07:35 UTC, closed without merging