19기)김근호 MISSION1. Django 초기세팅
wecode-bootcamp-korea/19-westagram-backend pull request #24
Opened 2021-04-05 06:38 UTC by astrocat9311

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장고 초기세팅 (mission1) 완료.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- - git 리포지토리 클론 --> student 폴더 안에 내 이름으로 된 디렉토리 생성 후 장고 프로젝트 & 앱 추가함
- - 가상환경은 wecode 사용 (django cors headers, 및 기타 필요한 패키지 설치)
- -  사용하지 않는 앱 , middleware 주석 처리  
- -  ALLOWED_HOSTS 추가
- - INSTALLED_APPS에 `corsheaders` 추가 + 위에서 생성한 앱 추가 
- - middleware에 `'corsheaders.middleware.CorsMiddleware'` 추가
- - urls.py` 에 사용하지 않는 코드 삭제

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-05 07:16 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/models.py
> +    #id = models.CharField(max_length=20, primary_key=True)
주석은 지워주세요!

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/models.py
> +
제일 긴 변수명 기준으로 컨벤션 맞춰주시고 불필요한 공백 없애주시면 좋을 거 같아요~

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/views.py
> +        user_db = User.objects.all()
이렇게 모든 유저 정보를 가져오지 않고 원하는 정보를 조회하는 방법을 생각해보시면 좋을 거 같아요!

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/views.py
> +        # data = json.loads(request.body)
주석처리된 불필요한 코드 지워주시면 훨씬 깔끔할 거 같아요~

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/views.py
> +                return JsonResponse({'message': 'use stronger password'}, status=400)
response 메세지는 error code를 텍스트화 하는 목적입니다.
해당하는 위코드 컨벤션은 {'message': 'EMAIL_ALREADY_EXIST'} 와 같은 형식인데 찾아보시고 수정해주세요!

2021-04-06 06:41 UTC, redsaumon commented on students/keunho-kim/westagram/users/views.py
> +            return JsonResponse({'message': 'SUCCESS'}, status=200)
제일 긴 변수명에 맞춰서 컨벤션 지켜주세요! status code 201이 어떤 의미인지 찾아보시고 적용해주시면 완벽할 거 같아요!

2021-04-06 11:43 UTC, Kang-kyunghun requested changes

2021-04-06 11:43 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +                return JsonResponse({'message': 'FILL_IN_EVERYTHING'}, status=400)
이거 어떤 경우를 의미하는 건가요?(질문)

2021-04-06 11:43 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +
공백은 1칸으로 해주세요.

2021-04-06 11:45 UTC, astrocat9311 commented on students/keunho-kim/westagram/users/views.py
> +                return JsonResponse({'message': 'FILL_IN_EVERYTHING'}, status=400)
저도 이부분 질문하려고 했었습니다. 구글링 하다보니, "데이터가 없다"는 표현을 이런식으로 코드를 작성하신 분이 있어서 가져왔는데.... 저도 이게 맞는지 모르겠습니다 ㅜㅜ.

2021-04-06 12:24 UTC, Kang-kyunghun requested changes

2021-04-06 12:24 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/models.py
> +    password     = models.TextField
TextField는 메모리를 많이 차지 합니다. CharField의 max_length을 조절하여 필드를 만들어 주세요.

2021-04-06 12:24 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +                return JsonResponse({'message': 'EMAIL_ALREADY_EXISTS'}, status=400)
메시지 내용의 통일감이 없습니다. 
```suggestion
                return JsonResponse({'message': 'DUPLICATED_INFORMATION'}, status=400)
```

2021-04-06 12:24 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +                return JsonResponse({'message': 'FILL_IN_EVERYTHING'}, status=400)
해당 if문을 어떤 이유로 사용 했는지 물어보는 것입니다.

2021-04-08 06:38 UTC, Kang-kyunghun requested changes
마무리 시간에 말했듯이 지나친 else 사용은 줄이는 것이 좋습니다.
논리적으로 어떻게 하면 else 없이 사용 할 수 있을지 생각해 보고 수정해 보세요.

2021-04-08 06:38 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +                if bcrypt.checkpw(data['password'].encode('utf-8'), user_email.password.encode('utf-8')) ==True:
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

2021-04-08 06:38 UTC, Kang-kyunghun commented on students/keunho-kim/westagram/users/views.py
> +
불필요한 공백은 제거해주세요.

2021-04-09 06:59 UTC, astrocat9311 commented on students/keunho-kim/westagram/users/views.py
> +                if bcrypt.checkpw(data['password'].encode('utf-8'), user_email.password.encode('utf-8')) ==True:
불린 값 모두 제거하고, 어제 나머지 세션(?)에서 지적하신 대로 수정했습니다~

2021-04-11 07:35 UTC, closed without merging