[19기 황수민] MISSION1. Django 초기세팅 완료
wecode-bootcamp-korea/19-westagram-backend pull request #25
Opened 2021-04-05 06:47 UTC by z132305

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장고 초기세팅 (mission1) 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
git 리포지토리 클론 --> student 폴더 안에 내 이름으로 된 디렉토리 생성 후 장고 프로젝트 & 앱 추가
가상환경은 test 사용 (django cors headers, 및 기타 필요한 패키지 설치)
사용하지 않는 앱 , middleware 주석 처리
ALLOWED_HOSTS ['*'] 추가
INSTALLED_APPS에 corsheaders 추가 + 생성한 앱 추가
middleware에 'corsheaders.middleware.CorsMiddleware' 추가
urls.py` 에 사용하지 않는 코드 삭제

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-05 07:27 UTC, Kang-kyunghun requested changes

2021-04-05 07:27 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/westagram/settings.py
> +DEBUG = False
디버그 모드 False로 한 이유가 따로 있으신가요?

2021-04-05 07:28 UTC, Kang-kyunghun commented
위에 남김 코멘트에 답만 달아주시고, 다음 미션 진행해 주세요.

2021-04-05 07:33 UTC, z132305 commented on students/sumin-hwang/westagram/westagram/settings.py
> +DEBUG = False
수정했습니다 !

2021-04-05 14:32 UTC, Kang-kyunghun requested changes

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/models.py
> +    email         = models.EmailField(max_length=200, unique=True, null=True)
email 같은 경우 필수로 들어와야 하는 값인데, null=True을 설정할 경우 어떤 상황이 발생할 수 있을까요?

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/models.py
> +    user_name     = models.CharField(max_length=100, unique=True)
name 과 user_name의 차이가 무엇인가요??(질문)

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +from users.models import User
import 라인 맞춰주세요.

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +
주석은 제거해 주세요.

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +        password      = data.get('password', None)
data.get을 사용한 이유를 설명해주세요.

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +        if User.objects.filter(user_name = data['user_name']):
```suggestion
        if User.objects.filter(user_name = data['user_name']).exists():
```
filter을 사용해서 존재 여부 판단 잘 하셨습니다.
보통 존재 여부만 판단 할 때는 .exists()를 붙여서 사용합니다.
filter을 사용할 경우 조건에 해당되는 데이터를 가져오지만, .exists()을 붙이면 존재 여부만 판단하고 데이터는 가져오지 않기 때문에 더 효율적입니다.

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +        elif mobile_number:
위의 if 조건이 True가 되어 코드가 동작한다면 return이 되기 때문에 굳이 elif로 조건을 묶으시지 않으셔도 됩니다.
아래 elif들도 정말 elif가 필요한 상황인지 생각해 보시고 수정해 주세요

2021-04-05 14:32 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +            print(mobile_number_form.match(mobile_number))
디버깅을 위한 print는 제거해 주세요

2021-04-06 04:11 UTC, z132305 commented on students/sumin-hwang/westagram/users/models.py
> +    user_name     = models.CharField(max_length=100, unique=True)
name = 성명
user_name = 사용자 이름(닉네임) 입니다 !

2021-04-06 08:26 UTC, z132305 commented
라인이 안맞는 곳이 많아서 라인 맞춰 수정 해 놓았습니다 !!

2021-04-06 08:56 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-06 12:01 UTC, Kang-kyunghun requested changes

2021-04-06 12:01 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +                    )
get 같은 경우는 조건을 확실히 특정 짓는 것이 좋습니다.

2021-04-06 12:01 UTC, Kang-kyunghun commented on students/sumin-hwang/westagram/users/views.py
> +                return JsonResponse({'MESSAGE':'PASSWORD_ERROR'}, status=401)
비밀번호가 일치하지 않는 경우를 if로 둔다면 else을 사용하지 않아도 되지 않을까요?

2021-04-07 09:13 UTC, redsaumon commented on students/sumin-hwang/westagram/users/views.py
> +                ).exists() == False:
해당 조건 자체로 Truthy, Falsy 한 값이라 == False를 사용하지 않아도 값을 확인할 수 있습니다.
다른 방법을 생각해주세요!

2021-04-08 09:32 UTC, redsaumon commented on students/sumin-hwang/westagram/users/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'})
어떤 값들을 response 해줘야할지 생각해봐주세요!

2021-04-08 10:38 UTC, z132305 commented on students/sumin-hwang/westagram/users/views.py
> +            return JsonResponse({'MESSAGE':'KEY_ERROR'})
except KeyError에 status 추가하였습니다!

2021-04-08 11:20 UTC, redsaumon commented
고생하셨습니다~

2021-04-11 07:35 UTC, closed without merging