[19기 홍태경] Feature/teagyeong
wecode-bootcamp-korea/19-westagram-backend pull request #28
Opened 2021-04-06 07:09 UTC by gusxoqkqh1

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 프로젝트 생성
- 프로젝트/셋팅 설정
- mysql 서버 설정
- 앱 생성
- migrate 생성
		 
## 수정 사항들 자세한 내용
- 프로젝트 명 :project_westagram
- app 명 : users
- db 명: users

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-06 07:12 UTC, gusxoqkqh1 commented
> > wecode PR message template 및 체크 리스트 입니다.
> > 아래 사항들을 전부 작성/체크 하시고 PR 해주세요!
> 
> ## 수정 사항 간략한 한줄 요약
> (여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
> 
> * 프로젝트 생성
> * 프로젝트/셋팅 설정
> * mysql 서버 설정
> * 앱 생성
> * migrate 생성
> 
> ## 수정 사항들 자세한 내용
> * 프로젝트 명 :project_westagram
> * app 명 : users
> * db 명: users
> 
> ## 기타 질문 및 특이 사항
> (궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
> 
> * 이메일 validation을 함수화할 수는 없나요? (예시)
> 
> ## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
> 조건을 만족한다면 각 빈칸에 x 표시 해주세요
> 
> * [ ]  필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
> * [ ]  Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
> * [ ]  제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
> * [ ]  본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-06 07:24 UTC, Kang-kyunghun commented
다음 미션 진행해 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun requested changes

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/models.py
> +    class meta:
공백 하나 추가해 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/models.py
> +    phone_num = models.CharField(max_length=50)
=을 기준으로 정렬해 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/urls.py
> +
불필요한 공백은 제거해 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +        requestpassword = 8
변수명이 뭔가 불확실 합니다. 그리고 상수는 대문자로만 이루어져 있는 것이 컨벤션입니다.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +
공백 제거해 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +                return JsonResponse({'message':'INVALID PASSWORD'},status=400)
if문 사이에 공백을 추가하여 가독성을 높여 주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +
공백은 1칸만 해주세요.

2021-04-06 11:53 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +                phone_num =data['phone_num']
=을 기준으로 정렬해 주세요.

2021-04-06 13:55 UTC, Kang-kyunghun requested changes

2021-04-06 13:55 UTC, Kang-kyunghun commented on students/taegyeong-hong/project_westagram/users/views.py
> +                return JsonResponse({'message':'INVALID PASSWORD'},status=400)
유효성 체크가 완료된 뒤에 데이터베이스에 접근하는 로직이 있는 것이 더 효율적입니다. 유효성 검사를 통과하지 못하면 데이터베이스에 굳이 접근하지 않아도 되기 때문입니다.

2021-04-08 04:43 UTC, gusxoqkqh1 commented on students/taegyeong-hong/project_westagram/users/views.py
> +                return JsonResponse({'message':'INVALID PASSWORD'},status=400)
멘토님, 먼저 코멘트 감사드립니다 제가 해주신 말을 이해를 못하겠습니다 저 2개의 유효성 부분에서 체크가 완료가 안된게 무엇인가요? 또, 데이터 베이스 로직에 접근한다는 말이 첫번째 '이메일이라는 쿼리셋이 존재한다면' 이라는 것 자체가 디비에 접근하여 조회를 하는 로직이라 보는데 혹시 맞나요? 조금만 더 힌트를 부탁드리겠습니다

2021-04-11 07:35 UTC, closed without merging