Feature/yunhyung
wecode-bootcamp-korea/19-westagram-backend pull request #30
Opened 2021-04-06 08:18 UTC by YunhyungLee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
- 초기세팅 완료
- 회원가입 엔드포인트 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환
- 이메일에 '@', '.' 없으면 에러 반환
- 비밀번호 8글자 미만 에러 반환
- 이메일, 폰넘버, 유저네임 중복시 에러 반환 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-06 11:46 UTC, Kang-kyunghun requested changes

2021-04-06 11:46 UTC, Kang-kyunghun commented on students/yunhyung-lee/project_westagram/users/models.py
> +    user_name   = models.CharField(max_length=30)
- 변수명은 확실히 해주세요.
- 이미 user 정보를 담고 있기 때문에 name로만 표현 하셔도 됩니다.
```suggestion
    phone_number   = models.CharField(max_length=30)
    name           = models.CharField(max_length=30)
```

2021-04-06 11:46 UTC, Kang-kyunghun commented on students/yunhyung-lee/project_westagram/users/views.py
> +
공백은 1칸으로 해주세요.

2021-04-06 11:55 UTC, YunhyungLee commented on students/yunhyung-lee/project_westagram/users/views.py
> +
위, 아래 공백 말씀이신가요?

2021-04-06 12:02 UTC, YunhyungLee commented on students/yunhyung-lee/project_westagram/users/models.py
> +    user_name   = models.CharField(max_length=30)
넵 수정했습니다 다시 푸시하겠습니다

2021-04-06 13:53 UTC, Kang-kyunghun requested changes
미션3 바로 진행해 주세요.

2021-04-06 13:53 UTC, Kang-kyunghun commented on students/yunhyung-lee/project_westagram/users/views.py
> +
import 다음에 class까지의 공백이요

2021-04-06 13:53 UTC, Kang-kyunghun commented on students/yunhyung-lee/project_westagram/users/views.py
> +                return JsonResponse({'MESSAGE': 'INVALID USER'}, status=401)
입력한 아이디가 없다는 것은 데이터베이스에 원하는 정보가 없다는 것이므로 404가 더 적절한 에러 같습니다. 해당 에러에 맞게 메시지도 수정해 주세요.

2021-04-06 13:53 UTC, Kang-kyunghun commented on students/yunhyung-lee/project_westagram/users/views.py
> +                return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
데이터베이스에 있는 비밀번호는 암호화 되어있기 때문에 무조건 if을 만족하지 못하고, 다음 retrun으로 넘어 갑니다. 현재 코드는 암호화된 비밀번호를 확인하는 코드로 절대 갈 수 없는 구조로 되어 있습니다. 수정해 주세요.

2021-04-07 08:58 UTC, Kang-kyunghun commented
고생하셨습니다~~~

2021-04-11 07:35 UTC, closed without merging