[19기 문희원] Mission1 Django 초기 셋팅
wecode-bootcamp-korea/19-westagram-backend pull request #9
Opened 2021-04-02 08:54 UTC by moonimooni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Mission1 Django 초기 셋팅
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 가상환경 생성
- 프로젝트 생성
- settings.py 초기 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-04-04 08:33 UTC, Kang-kyunghun commented
미션1 완료!! 다음 미션 진행해 주세요.

2021-04-05 02:19 UTC, Kang-kyunghun requested changes

2021-04-05 02:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/models.py
> +    updated_at  = models.DateTimeField(auto_now=True)
```suggestion
    email      = models.EmailField(max_length=200, unique=True)
    password   = models.CharField(max_length=200)
    nickname   = models.CharField(max_length=100, unique=True)
    phone      = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
```
가장 긴 변수명 기준으로 한 칸 정도만 띄우면 될 것 같습니다.

2021-04-05 02:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
except 안에 return이 있으면 어떻게 될까요?
try문 안에서 에러가 발생하지 않는다면, else가 없어도 정상적으로 return이 되지 않을까요? 
한 번 생각해 보시고 의견 달아주세요.

2021-04-05 02:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +from .helpers               import email_validator, password_validator, phone_validator
```suggestion
from django.views import View
from django.http  import JsonResponse

from .models      import User
from .helpers     import email_validator, password_validator, phone_validator
```
이 부분도 가장 긴 것 기준으로 한 칸만 띄우셔도 될 것 같아요

2021-04-05 02:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/helpers.py
> +    return False
비밀번호 8자리 이상도 해당 정규 표현식으로 커버가 되나요?(질문)

2021-04-05 02:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +from .helpers               import email_validator, password_validator, phone_validator
helpers 보다는 utils나 validators가 조금 더 의미를 명확히 하지 않을까 싶어요(의견)

2021-04-05 04:46 UTC, moonimooni commented on students/heewon-moon/westagram/users/views.py
> +            return JsonResponse({'MESSAGE' : 'SUCCESS'}, status=200)
else문을 쓰는게 좀 더 코드의 작성의도가 명확하게 드러나고 가독성도 좋지 않나요?

파이썬 공식문서에서도 else문 사용을 권유하는 걸로 알고 있어서요.
catch하고 싶지 않은 error를 넘기려는 이유도 있지만,
지금 저의 코드에서는 작성 의도를 명확하게 드러내기 위한 목적이 더 컸습니다.

제가 stackoverflow에서 찾아본 링크도 걸어봅니다!
https://stackoverflow.com/questions/855759/python-try-else

2021-04-05 04:54 UTC, moonimooni commented on students/heewon-moon/westagram/users/views.py
> +from .helpers               import email_validator, password_validator, phone_validator
넵 수정하겠습니다~!

2021-04-05 07:42 UTC, Kang-kyunghun requested changes

2021-04-05 07:42 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +            phone       = data['phone']
가장 긴 변수 기준으로 맞추어 주세요.

2021-04-05 07:42 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +                phone       = phone
가장 긴 변수 기준으로 맞춰주세요.

2021-04-06 05:17 UTC, Kang-kyunghun requested changes
공백만 제거 하시고 다음 미션 진행하세요.

2021-04-06 05:17 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +
공백은 1칸만 주셔도 충분합니다.

2021-04-06 05:53 UTC, moonimooni commented
아 import 줄 맞추는걸 깜빡했네요 ㅠㅠㅠㅠㅠ 수정했습니다~!

2021-04-06 08:19 UTC, Kang-kyunghun requested changes

2021-04-06 08:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +        except User.DoesNotExist:
except로 get을 사용 하여 데이터가 없을 때를 잘 처리하셨습니다.
위와 같은 상황에 대해 예외처리 하는 방법으로는 filter와 exists()을 사용해서 할 수도 있습니다.
이러한 방법이 except로 넘기는 방법보다 조금 더 효율적일 수 있습니다.

2021-04-06 08:19 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +                user = User.objects.get(nickname=account)
해당 로직을 말로 한 번 풀어 주실 수 있을까요?(요청)

2021-04-06 08:43 UTC, moonimooni commented on students/heewon-moon/westagram/users/views.py
> +                user = User.objects.get(nickname=account)
user는 로그인시 email, phone number, nickname을 모두 이용할 수 있지만, 
백엔드 입장에서는 어떤 종류를 입력할지 알 수 없습니다. (여기서는 임의로 account라고 명칭했습니다.)
따라서 회원가입시 사용했던 정규표현식을 통해 account가 email인지, phone number인지, nickname인지 구분하고 user를 정의했습니다.
그 어디에도 해당하지 않으면 user 변수 호출시 
User.DoesNotExists 에러가 뜨기 때문에 거기서 INVALID USER 메세지를 보냈습니다.

2021-04-06 12:35 UTC, Kang-kyunghun requested changes

2021-04-06 12:35 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID PHONE NUMBER'}, status=400)
이 부분을 지금 발견 했네요.
데이터베이스에 접근하는 로직보다 유효성 검사를 하는 부분이 앞에 있는 것이 더 효율적 입니다.
유효성 검사를 통과하지 못하면 굳이 데이터베이스에 접근하지 않아도 되기 때문입니다.

2021-04-06 12:35 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +            user = User.objects.filter(Q(email=account) | Q(phone=account) | Q(nickname=account))
Q가 어떤식으로 동작 할까요?

2021-04-06 12:35 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +                return JsonResponse({'MESSAGE' : 'INVALID USER'}, status=401)
아이디가 일치하지 않았다는 것은 원하는 자원이 없다는 것이므로 상태 코드는 404가 더 적절할 것 같습니다.

2021-04-06 12:35 UTC, Kang-kyunghun commented on students/heewon-moon/westagram/users/views.py
> +            user = user[0]
인데스를 하드코딩 하여 데이터를 가져오는 것은 안 좋은 방법입니다.
쿼리셋인데 무조건 한 가지만 나오는 경우라면 first()을 사용해 주세요.

2021-04-07 07:36 UTC, Kang-kyunghun commented
LGTM!!! 고생하셨습니다.

2021-04-11 07:35 UTC, closed without merging